/** Central runtime configuration for rendering, audio, interaction, and procedural generation. */
export const gameConfig = {
  scene: {
    pathPalette: ["#ffaf45", "#58c4dd", "#ffc857", "#ff7f7f", "#b291ff", "#7bd389"],
    backgroundColor: "#0f1718",
    fogDensity: 0.02,
    camera: {
      fov: 50,
      near: 0.1,
      far: 100,
      initialTarget: { x: 3.5, y: 0, z: 2.5 },
      initialYaw: Math.PI / 2,
      initialPitch: 0.82,
      initialDistance: 13.5,
      rotateYawSpeed: 0.0035,
      rotatePitchSpeed: 0.003,
      pitchMin: 0.0,
      pitchMax: Math.PI / 2,
      panDistanceFactor: 0.00115,
      zoomFactor: 0.0012,
      minDistance: 6.5,
      maxDistance: 28,
      fitDistanceFactor: 1.7,
      fitDistanceMin: 8,
      fitDistanceMax: 26,
      targetPadding: 3.5,
    },
    lights: {
      ambient: {
        color: "#ffffff",
        intensity: 0.32,
      },
      keyDirectional: {
        color: "#ffffff",
        intensity: 1.9,
        position: { x: 6, y: 12, z: 4 },
        shadowMapSize: 1024,
        shadowRadius: 2,
        shadowBias: -0.00012,
        shadowNormalBias: 0.02,
        shadowNear: 0.5,
        shadowFar: 80,
        shadowSpanFactor: 0.9,
        shadowSpanPadding: 3,
      },
      topDirectional: {
        color: "#ffffff",
        intensity: 1.15,
        position: { x: 0, y: 20, z: 0 },
      },
      topPoint: {
        color: "#fff4d6",
        intensity: 10.5,
        distance: 12,
        decay: 1.0,
        height: 3.8,
      },
    },
    path: {
      verticalOffset: 0.08,
      perPathLift: 0.003,
      overlapOffsetStep: 0.06,
      opacity: 0.95,
    },
    hitPulse: {
      durationBeats: 0.52,
      colors: {
        matched: "#1db65f",
        wrong: "#d63b35",
        empty: "#f1f1f1",
      },
      emptyOpacity: 0.5,
      defaultOpacity: 1.0,
      emptyScale: 0.1,
      defaultScale: 0.9,
      emptyGrowth: 0.6,
      defaultGrowth: 1.3,
      y: 0.02,
    },
    preview: {
      invalidColor: "#ff5f57",
      validLightenAmount: 0.3,
    },
    mesh: {
      buttonBlockInset: 0.08,
      buttonBlockHeight: 0.24,
      buttonBlockRoughness: 0.82,
      buttonBlockMetalness: 0.04,
      iconMinimumSize: 0.4,
      iconScaleFactor: 0.52,
      iconY: 0.125,
      buttonPickProxyHeight: 0.26,
      terrainPickProxyHeight: 0.12,
      hitPulse: {
        innerRadius: 0.3,
        outerRadius: 0.42,
        segments: 40,
        opacity: 0.88,
      },
      obstacleFallbackHeight: 0.55,
      obstacleFallbackRoughness: 0.88,
      obstacleFallbackMetalness: 0.04,
    },
    blockPress: {
      depth: 0.1,
      scaleY: 0.52,
    },
    terrain: {
      y: 0,
    },
    animal: {
      fallbackRadius: 0.25,
      fallbackSegments: 16,
      fallbackY: 0.3,
      modelScale: 0.35,
      modelY: 0.18,
      lookAheadBeat: 0.05,
      movementEpsilon: 0.0001,
      jumpHeight: 0.55,
    },
    blockModel: {
      minimumScaleAxis: 1e-6,
    },
  },
  audio: {
    storageKey: "animal-groove-audio-mix",
    lookAhead: 0.01,
    scheduleLeadTime: 0.003,
    minimumScheduleGap: 0.0005,
    defaultMix: {
      hit: { volume: 1.05, muted: false },
      reference: { volume: 0.18, muted: false },
      wrong: { volume: 0.4, muted: false },
    },
    triggerVelocity: {
      matched: 0.95,
      wrong: 0.5,
      reference: 0.45,
    },
    foley: {
      gainFactor: 0.72,
      minimumGain: 0.05,
      maximumGain: 1.8,
      fadeOut: 0.03,
      sources: {
        sand: "./SE/step_sand.mp3",
        puddle: "./SE/step_puddle.mp3",
        leaf: "./SE/step_leaf.mp3",
      },
    },
    synth: {
      hit: {
        oscillator: "triangle",
        envelope: { attack: 0.003, decay: 0.08, sustain: 0.08, release: 0.08 },
      },
      wrong: {
        oscillator: "square",
        envelope: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.035 },
      },
      reference: {
        oscillator: "sine",
        envelope: { attack: 0.004, decay: 0.12, sustain: 0, release: 0.05 },
      },
    },
    filters: {
      wrongHighpassHz: 1800,
      referenceLowpassHz: 500,
    },
    durations: {
      hit: "16n",
      wrong: "32n",
      reference: "16n",
    },
    pitches: {
      kick: "C2",
      snare: "G2",
      hat: "C4",
      clap: "D4",
      tom: "F2",
      default: "A3",
    },
  },
  interaction: {
    pressedWindowBeats: 0.22,
    beatCrossEpsilon: 0.0001,
  },
  timeline: {
    preferredLanes: ["kick", "snare", "hat"],
    curveToleranceMin: 0.08,
    curveToleranceLoopRatio: 0.02,
    pulseWidthMin: 0.08,
    pulseWidthLoopRatio: 0.018,
    minimumAmplitude: 0.15,
    topPadding: 7,
  },
  generation: {
    defaultLoopBeatOptions: [6, 8],
    defaultGeneratedBpm: 112,
    randomLevelBpmBase: 96,
    randomLevelBpmRange: 33,
    generatedAnimalTypes: ["fox", "dog", "bee", "tiger", "parrot", "bunny"],
    timbrePalette: {
      kick: "#ffaf45",
      snare: "#58c4dd",
      hat: "#ffc857",
      sand: "#d4b483",
      puddle: "#5f9ed6",
    },
    judgeBeatTolerance: 0.12,
    targetBlockCount: {
      min: 6,
      max: 16,
      loopBeatFactor: 1.25,
      animalCountFactor: 1,
    },
  },
};
